// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhMBkRD49SMgrYfKSiXz6RvkXQ4An67ak',
    appId: '1:351442774180:web:532be8a350d61cde5f9e31',
    messagingSenderId: '351442774180',
    projectId: 'crowdwave-93d4d',
    authDomain: 'crowdwave-93d4d.firebaseapp.com',
    storageBucket: 'crowdwave-93d4d.firebasestorage.app',
    measurementId: 'G-GZ6BHCQFY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn3TkF-M_d8ICAISbEtOmaA20k-C5niks',
    appId: '1:351442774180:android:d05be8c16c5c21445f9e31',
    messagingSenderId: '351442774180',
    projectId: 'crowdwave-93d4d',
    storageBucket: 'crowdwave-93d4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjTQRuf09ontEdiaEVYkN2uLMPIQO6qbA',
    appId: '1:351442774180:ios:458a93fdce711c515f9e31',
    messagingSenderId: '351442774180',
    projectId: 'crowdwave-93d4d',
    storageBucket: 'crowdwave-93d4d.firebasestorage.app',
    iosBundleId: 'com.example.login_register',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhMBkRD49SMgrYfKSiXz6RvkXQ4An67ak',
    appId: '1:351442774180:web:532be8a350d61cde5f9e31',
    messagingSenderId: '351442774180',
    projectId: 'crowdwave-93d4d',
    storageBucket: 'crowdwave-93d4d.firebasestorage.app',
    iosBundleId: 'com.example.login_register',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhMBkRD49SMgrYfKSiXz6RvkXQ4An67ak',
    appId: '1:351442774180:web:532be8a350d61cde5f9e31',
    messagingSenderId: '351442774180',
    projectId: 'crowdwave-93d4d',
    storageBucket: 'crowdwave-93d4d.firebasestorage.app',
  );
}
